### ISSUE TITLE
It is possible to set the hitbox dimensions to zero

### ISSUE THREAD

**Issue by GO-Miles** [harpwood/FlxSprite-Inspector#2]
Expected behavior:
Setting the scaleX or scaleY to 0 prevents the hitbox from being updated when "update hitbox" is clicked.
Setting the width or height to zero is prevented.

Observed behavior:
Setting the scaleX or scaleY to 0 updates the hitbox accordingly.
Setting the width or height to zero is allowed.
crashes

**Comment by GO-Miles** [comment]
Despite the bug, this release looks solid! I plan on pushing some changes while I'm home sick, with a couple of them circumventing this one. Expect runtime shaders, mouse support, and image loading once I'm feeling better!

**Comment by harpwood** [comment]
Thank you very much for your time, effort and dedication!

I cannot reproduce the bug. Can you elaborate more or even record a short clip demonstrating it?

Maybe for shaders is a good idea to make a dedicated gamestate to avoid over-clutter to UI; something like ShaderInspector.hx

I was thinking to add  [ColorMatrixFilter ](https://api.openfl.org/openfl/filters/ColorMatrixFilter.html) inspection abilities and tweaking and put them in a dedicate gamestate, something like ColorMatrixFilter.hx

My next step is to make a child class of the FlxSpriteInspector and re-enable your skew implementation. The reason I temporally disable it, is that it is requires a FlxSkewedSprite, making a dedicated inspection class makes more sense. The next online demo will demonstrate the skew capabilities as well!

**Comment by harpwood** [comment]
Additionally, I cannot find the point of image loading. This project is about a set of tools that you temporally import them in your game project in order to make your gamedev easier. Can you say more about it and how you have envisioned it?

**Comment by GO-Miles** [comment]
It depends on whether your primary focus is developing a toolkit or a standalone web app. My current idea was to build something that helps people learn about and edit the properties of FlxSprites, but your point made me realize I've neglected its main utility, which is debugging in an existing project. Loading images from outside the project wouldn't make sense, but handling complex assets in the project with child classes sounds like a must. For starters, should this be made into a haxelib?

**Comment by GO-Miles** [comment]
> I cannot reproduce the bug. Can you elaborate more or even record a short clip demonstrating it?

While it could be a myriad of issues, I can replicate it on windows:

https://github.com/harpwood/FlxSprite-Inspector/assets/95124554/adc63fe4-a0ea-4756-ab7f-b3b5575f3070

**Comment by harpwood** [comment]
Thank you for taking the time to record a video showcasing the issue. I was able to reproduce it, and I'm glad to inform you that it was an easy fix!

> For starters, should this be made into a haxelib?

Yes, I believe it will be our best bet. By turning it into a library, we can focus on refining and stabilizing the core functionality before considering a standalone web app version in the future. This approach allows us to provide a more polished and reliable experience for users. 

In the provided image, the left side showcases the current project structure, while the right side represents the structure I propose, with the condition that I will successfully separate the sprite view logic from the UI logic in a meaningful way. This separation is aimed at improving the project's scalability and maintainability. I would appreciate your thoughts and feedback on this approach. If you have any alternative suggestions or ideas, please feel free to share them as well.
![image](https://github.com/harpwood/FlxSprite-Inspector/assets/44503874/2c8fd0a7-5545-44ff-b426-f49919ebb93b)

**Comment by GO-Miles** [comment]
I think your suggestion nails it!

A base inspector state could contain the sprite, keybind logic to increment/decrement/alter values, and UI getter/setter elements for inspector classes to use.
An inspector class could define what changes, and contain logic needed to change it.

Beyond basic properties, a setup like this will be very scalable! For example, SkewInspector would alter the sprite's matrix values like the class itself does, which gives DinoSprite or any other FlxSprite class said functionalities. Implementing separate logic to calculate for existing properties instead of extending doesn't present inheritance issues like my skewing commit did!

![very modular image](https://github.com/harpwood/FlxSprite-Inspector/assets/95124554/ef5401a3-42fd-4fc4-a420-ae97bd459827)

Private access, state instances, and reflections aside, it doesn't get easier than this image. Thanks for asking for my feedback!
